/**
 * PILAR AUTOPILOT - OpenAI Adapter
 * 
 * Handles AI text generation for WhatsApp Coach and support reports
 * Gracefully degrades when ENV not configured
 */

import { IOpenAIAdapter, IAdapterResult } from './base'
import { logger } from '@/lib/logger'
import { withRetry } from '@/lib/autopilot/self-healing'
import OpenAI from 'openai'

const OPENAI_API_KEY = process.env.OPENAI_API_KEY

class OpenAIAdapterImpl implements IOpenAIAdapter {
  private client: OpenAI | null = null

  constructor() {
    if (OPENAI_API_KEY) {
      this.client = new OpenAI({
        apiKey: OPENAI_API_KEY,
      })
    }
  }

  private isConfigured(): boolean {
    return !!this.client
  }

  async generateCoachMessage(context: {
    tone: string
    goal: string
    lastMessages: string[]
    language: 'DE' | 'EN'
    leadName?: string
    targetAudience?: string
  }): Promise<
    IAdapterResult<{
      text: string
    }>
  > {
    if (!this.isConfigured()) {
      logger.warn('OpenAI not configured, skipping coach message generation')
      return {
        ok: false,
        error: 'OpenAI not configured',
        code: 'INTEGRATION_OFFLINE',
      }
    }

    try {
      const systemPrompt = `Du bist ein motivierender Fitness-Coach für ein Fitnessstudio. 
Deine Aufgabe ist es, personalisierte WhatsApp-Nachrichten zu schreiben, die Mitglieder motivieren und unterstützen.

Tonalität: ${context.tone}
Zielgruppe: ${context.targetAudience || 'Fitnessstudio-Mitglieder'}
Trainingsziel: ${context.goal}

Schreibe kurze, persönliche Nachrichten (max. 2-3 Sätze), die:
- Motivierend und positiv sind
- Zum Training ermutigen
- Auf das Trainingsziel eingehen
- Authentisch und nicht zu werblich klingen
- Emojis sparsam einsetzen (max. 1-2)

Sprache: ${context.language === 'DE' ? 'Deutsch' : 'English'}`

      const userPrompt = `Schreibe eine motivierende WhatsApp-Nachricht${context.leadName ? ` an ${context.leadName}` : ''}.

${context.lastMessages.length > 0 ? `Letzte Nachrichten:\n${context.lastMessages.slice(-3).join('\n')}\n\n` : ''}

Schreibe eine neue, passende Nachricht:`

      const completion = await withRetry(async () => {
        if (!this.client) {
          throw new Error('OpenAI client not initialized')
        }

        return await this.client.chat.completions.create({
          model: 'gpt-4o-mini',
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: userPrompt },
          ],
          temperature: 0.8,
          max_tokens: 200,
        })
      })

      const text = completion.choices[0]?.message?.content?.trim()

      if (!text) {
        throw new Error('No text generated by OpenAI')
      }

      logger.info(
        { tone: context.tone, goal: context.goal, textLength: text.length },
        'Coach message generated'
      )

      return {
        ok: true,
        data: { text },
      }
    } catch (error: any) {
      logger.error({ error, context }, 'Failed to generate coach message')
      return {
        ok: false,
        error: error.message || 'Failed to generate message',
        code: error.code || 'WEBHOOK_ERROR',
      }
    }
  }

  async generateSupportReport(context: {
    workspaceId: string
    errors: Array<{
      message: string
      timestamp: string
      step?: string
    }>
    jobType: string
  }): Promise<
    IAdapterResult<{
      summary: string
      recommendations: string[]
    }>
  > {
    if (!this.isConfigured()) {
      logger.warn('OpenAI not configured, skipping support report generation')
      return {
        ok: false,
        error: 'OpenAI not configured',
        code: 'INTEGRATION_OFFLINE',
      }
    }

    try {
      const systemPrompt = `Du bist ein technischer Support-Assistent für PILAR SYSTEMS.
Deine Aufgabe ist es, Fehlerberichte zu analysieren und prägnante Zusammenfassungen für das Support-Team zu erstellen.

Erstelle einen strukturierten Bericht mit:
1. Kurze Zusammenfassung des Problems (1-2 Sätze)
2. Liste von konkreten Handlungsempfehlungen (3-5 Punkte)

Sprache: Deutsch, technisch aber verständlich.`

      const userPrompt = `Workspace ID: ${context.workspaceId}
Job Type: ${context.jobType}

Fehler (${context.errors.length} insgesamt):
${context.errors.map((e, i) => `${i + 1}. [${e.timestamp}] ${e.step ? `Step: ${e.step} - ` : ''}${e.message}`).join('\n')}

Erstelle einen Support-Bericht:`

      const completion = await withRetry(async () => {
        if (!this.client) {
          throw new Error('OpenAI client not initialized')
        }

        return await this.client.chat.completions.create({
          model: 'gpt-4o-mini',
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: userPrompt },
          ],
          temperature: 0.3,
          max_tokens: 500,
        })
      })

      const response = completion.choices[0]?.message?.content?.trim()

      if (!response) {
        throw new Error('No response generated by OpenAI')
      }

      const lines = response.split('\n').filter((l) => l.trim())
      const summary = lines[0] || 'Fehler bei der Provisioning'
      const recommendations = lines
        .slice(1)
        .filter((l) => l.match(/^[\d\-\*•]/))
        .map((l) => l.replace(/^[\d\-\*•.\s]+/, '').trim())
        .filter((l) => l.length > 0)

      logger.info(
        { workspaceId: context.workspaceId, errorCount: context.errors.length },
        'Support report generated'
      )

      return {
        ok: true,
        data: {
          summary,
          recommendations: recommendations.length > 0 ? recommendations : ['Bitte manuell prüfen'],
        },
      }
    } catch (error: any) {
      logger.error({ error, context }, 'Failed to generate support report')
      return {
        ok: false,
        error: error.message || 'Failed to generate report',
        code: error.code || 'WEBHOOK_ERROR',
      }
    }
  }
}

export const openaiAdapter = new OpenAIAdapterImpl()
